sonar.organization=lifeson
sonar.projectKey=lifeson_Front-end---Testez-et-am-liorez-une-application-existante
sonar.projectName=Front-end - Testez et améliorez une application existante

# Code source vs code de test
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

# Rapport de couverture Jest (TS inclus)
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Fichiers exclus du calcul de couverture (pas de logique métier à tester)
sonar.coverage.exclusions=\
  src/main.ts,\
  src/**/*.spec.ts,\
  src/app/**/*.module.ts,\
  src/app/app.config.ts,\
  src/app/app.routes.ts

sonar.sourceEncoding=UTF-8